### PR TITLE
Parse variables in command

### PR DESCRIPTION
**Pull request by llamafilm**

### CODE REVIEW

**Review by JeffreyDavidsz — CHANGES_REQUESTED** [review]
textwithvariables is not a thing... you could do a pull against the core or see how other modules handle it like vicreo-variablelistener

**Comment by llamafilm** [comment]
@JeffreyDavidsz can you clarify what you mean by "not a thing"?  I'm new to this project so I may be misunderstanding, but I believe the `textwithvariables` field type is defined [here].(https://github.com/bitfocus/companion/blob/86711173506bac03f137c7775d347db9a4e09ff6/instance_skel_types.d.ts#L111).

I referenced the [Generic HTTP](https://github.com/bitfocus/companion-module-generic-http/blob/de56b46ccc299cbd331254f533c8238521dd4292/index.js#L92) module to see how this was implemented.

**Comment by JeffreyDavidsz** [comment]
I see, my bad it seems its a thing. I'm getting an error though I need to check why

**Comment by JeffreyDavidsz** [comment]
Found it, I'll do a new commit as I just re-wrote this to ES6

**Comment by llamafilm** [comment]
Ok thanks!  I just pulled the latest companion master branch which includes this module version 1.0.8 but it fails to start.  Do you know what causes this?  I use node 14.18.2.

```
$ node headless_ip 0.0.0.0
Starting
Started
/home/ubuntu/companion/node_modules/companion-module-generic-tcp-udp/index.js:95
				this.status(status, message)
				     ^

TypeError: this.status is not a function
    at tcp.<anonymous> (/home/ubuntu/companion/node_modules/companion-module-generic-tcp-udp/index.js:95:10)
    at tcp.emit (events.js:400:28)
    at new_status (/home/ubuntu/companion/tcp.js:34:8)
    at Socket.<anonymous> (/home/ubuntu/companion/tcp.js:98:3)
    at Socket.emit (events.js:412:35)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:10)
```

**Comment by JeffreyDavidsz** [comment]
I'll check it for you

**Comment by JeffreyDavidsz** [comment]
Should be fixed now

**Comment by llamafilm** [comment]
Yes it works now, thanks

**Comment by kjetilpp** [comment]
How to use this? This is not working OUT00:$(internal:custom_MATin). :)

**Comment by JeffreyDavidsz** [comment]
Add the moment, it will check the whole field as is one variable. So try to put the OUT00: in the variable to. Add an issue for this to filter out variables if you need that

**Pull request closed without merging**
